### ISSUE TITLE
增加关键训练报错，把2个改成5了关键点，报错：Target size (torch.Size([7, 5])) must be the same as input size (torch.Size([7, 2]))

### ISSUE THREAD

**Issue by 1095788063** [xialuxi/yolov7-landmark#4]
![1](https://user-images.githubusercontent.com/29217820/191317801-b75af1a1-3d78-4d8c-b81d-9c4d697154a1.JPG)

![Uploading 2.JPG…]()

     Epoch   gpu_mem       box       obj       cls       kpt      kptv     total    labels  img_size
  0%|          | 0/14 [00:03<?, ?it/s]
pkpt_score= tensor([[ 1.30273, -0.51270],
        [ 1.50098, -0.30347],
        [ 1.50098, -0.30347],
        [ 1.50098, -0.30347],
        [ 0.22461, -1.61426],
        [ 0.22461, -1.61426],
        [ 0.80762, -0.86426]], device='cuda:0', dtype=torch.float16, grad_fn=<SliceBackward>)
kpt_mask= tensor([[0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1.],
        [0., 1., 1., 0., 1.]], device='cuda:0')
Traceback (most recent call last):
  File "G:/code/yolo/yolov7/yolov7-landmark-main/train.py", line 623, in <module>
    train(hyp, opt, device, tb_writer)
  File "G:/code/yolo/yolov7/yolov7-landmark-main/train.py", line 372, in train
    loss, loss_items = compute_loss_ota(pred, targets.to(device), imgs)  # loss scaled by batch_size
  File "G:\code\yolo\yolov7\yolov7-landmark-main\utils\loss.py", line 719, in __call__
    lkptv += self.BCEcls(pkpt_score, kpt_mask)
  File "D:\Python\Python38_pytorch_1_8_1\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Python\Python38_pytorch_1_8_1\lib\site-packages\torch\nn\modules\loss.py", line 714, in forward
    return F.binary_cross_entropy_with_logits(input, target,
  File "D:\Python\Python38_pytorch_1_8_1\lib\site-packages\torch\nn\functional.py", line 2827, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([7, 5])) must be the same as input size (torch.Size([7, 2]))

**Comment by xialuxi** [comment]
很明显是维度不对， 你的数据格式是什么样的？

**Comment by 1095788063** [comment]
可以出一个支持训练多点的版本么，我的是5个点的，改了很多地方还是有些问题。

**Comment by 1095788063** [comment]
我看了代码是很多地方写死固定了2个点的训练的

**Comment by sabahmax-inc** [comment]
Hi, thanks for reporting! I’ve opened PR #6 to fix this training error. It resolves the keypoint loss shape mismatch after changing the keypoint count from 2 to 5, so `pkpt_score` and `kpt_mask` now have matching sizes. Here’s the PR: https://github.com/xialuxi/yolov7-landmark/pull/6
